
# This is a basic workflow to help you get started with Actions

name: CI
on:
  pull_request:
  push:
    branches: [ master ]
jobs:
  build:
    name: Building and Pushing the Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: gitops
        IMAGE_TAG: latest

      run: |
        # Build a docker container and push it to ECR
        cd app/
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest . 
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        
        
